org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Environment properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.242
loader_version_range=[1,)

# Mod properties
mod_id=mirrorsync
mod_name=MirrorSync
mod_license=All Rights Reserved
mod_version=1.0.2
mod_group_id=com.mcstaralliance.mirrorsync
mod_authors=remering
mod_description=Automatically synchronizes Minecraft client files from a remote manifest.
